### ISSUE TITLE
Placeholders for OP players

### ISSUE THREAD

**Issue by Askarionn** [yapzhenyie/GadgetsMenu#880]
**Describe the bug**
If you're OP the placeholders for locked categories are not working good

**To Reproduce**
1. Use any locked category placeholder
2. See error

**Expected behavior**
It should show the correct number of locked items

**Further Information (please complete the following information):**
 - Server Version: 1.8.8
 - GadgetsMenu Version: 5.0.7

**Screenshots**
https://imgur.com/a/5kE19Pb

**Additional Information**
-

**Comment by yapzhenyie** [comment]
Thank you for reporting this issue, it will be fixed in the next update.

**Comment by yapzhenyie** [comment]
This issue has been fixed. Please check for the new update.

**Comment by Askarionn** [comment]
Hello! On latest update just the problem with placeholder for locked Animated Hats has been fixed.
But if i'm OP i still see 0 on all locked placeholders

**Comment by yapzhenyie** [comment]
> Hello! On latest update just the problem with placeholder for locked Animated Hats has been fixed. But if i'm OP i still see 0 on all locked placeholders

That's normal, OP player has access to all cosmetic items
